name: Build Node Firmware

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run script
        shell: bash
        working-directory: scripts
        run: ./scripts/build.sh
