name: Build Node Firmware

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run script
        shell: bash
        run: ./scripts/build.sh

      - name: where are you
        run: ls ~/work/node

      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r dir.zip ~/work/node/tester.txt
      
      - uses: actions/upload-artifact@v2
        with:
          name: dir.zip

      # - name: Release with Notes
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     files: ~/work/node/tester.zip
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      # - name: Release
      #   uses: softprops/action-gh-release@v1

      # - uses: AButler/upload-release-assets@v2.0
      #   with:
      #     files: ~/work/micropython/ports/esp32/build-GENERIC/firmware.bin
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
      #     release-tag: ${{ github.ref }}
