name: Build Node Firmware

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run script
        shell: bash
        run: ./scripts/build.sh

      - name: where are you
        run: ls ~/work/node

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file:  ~/work/node/tester.sh
          tag: ${{ github.ref }}

      # - name: Release
      #   uses: softprops/action-gh-release@v1

      # - uses: AButler/upload-release-assets@v2.0
      #   with:
      #     files: ~/work/micropython/ports/esp32/build-GENERIC/firmware.bin
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
      #     release-tag: ${{ github.ref }}
