name: Build Node Firmware

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run script
        shell: bash
        run: ./scripts/build.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ~/work/micropython/ports/esp32/build-GENERIC/firmware.bin
