name: Build Node Firmware

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run script
        shell: bash
        run: ./scripts/build.sh

      - name: where are you
        run: ls ~/work/node

      - name: Upload release attachment
        uses: actions/github-script@v4
        with:
          script: |
            console.log(ls)