name: Build Node Firmware

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run script
        shell: bash
        run: ./scripts/build.sh

      - name: where are you
        run: ls ~/work/node

      - name: Upload release attachment
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs');
            const { repo: { owner, repo }, sha } = context;
            console.log({ owner, repo, sha });
            // Get release for this tag
            const release = await github.repos.createRelease({
              owner, repo,
              tag_name: process.env.GITHUB_REF,
              draft: true,
              target_commitish: sha
            });

            // Upload the release asset
            await   ({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.data.id,
              name: "test.sh",
              data: await fs.readFileSync("~/work/node/tester.sh")
            });

      # - name: Release
      #   uses: softprops/action-gh-release@v1

      # - uses: AButler/upload-release-assets@v2.0
      #   with:
      #     files: ~/work/micropython/ports/esp32/build-GENERIC/firmware.bin
      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
      #     release-tag: ${{ github.ref }}
